### ISSUE TITLE
[4pt] - Generate controllers for Food and RecipeFood, add basic views

### ISSUE THREAD

**Issue by hajnaloltyan** [hajnaloltyan/recipe-app#10]
- Generate the controllers, with methods for index and show
- Create Foods table as an index file
- Create the Food table for all individual recipe pages, when the basic recipe pages are created
- Create Shopping List view
- Add routes

**Comment by CVILLA09** [comment]
Visit Pages in the Browser: Use a web browser to navigate to the different routes you've set up:

Root path (e.g., http://localhost:3000/) to see the recipes index.
Foods path (e.g., http://localhost:3000/foods) to see the foods table.
Recipe foods path (e.g., http://localhost:3000/recipes/:recipe_id/recipe_foods) to see the foods for a specific recipe.
Shopping list path (e.g., http://localhost:3000/foods/shopping_list) to see the shopping list.
